[ea_rf]
ch1 = BNC
ch2 = N-type
# max_power_ch1 = -13
# max_power_ch2 = -23
max_power_ch1 = -9.5
max_power_ch2 = 8
frequency = 24000000
oscillo = class
power_unit = vpp
frequency_unit = kHz

[ec_rf]
ch1 = BNC
ch2 = N-type
# max_power_ch1 = -11
# max_power_ch2 = -39
max_power_ch1 = -8
max_power_ch2 = 8
frequency = 32000000
oscillo = class
power_unit = vpp
frequency_unit = kHz

[aom400]
curr_channel = CH2
oscillo_MSO7054 = class